---
title: "checking for false positives"
output: html_document
date: "2024-03-28"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

load gadid aquaria data 
```{r}
aquaria_data <- read.csv("/home/kimberly.ledger/gadid_aquaria/gadid_mb_aquaria/aquaria_taxonreads_20240313.csv") %>%
  dplyr::select(!X) %>%
  dplyr::select(!sample_type) %>%
  rename(tank_ID = site) %>%
  group_by(tank_ID, taxon) %>%
  summarize(reads = sum(total_reads)) %>%
  group_by(tank_ID) %>%
  mutate(total_reads = sum(reads)) %>%
  mutate(prop_reads = reads/total_reads)
```

read in tank metadata
```{r}
metadata <-  read.csv("/home/kimberly.ledger/gadid_aquaria/gadid_mb_aquaria/TankData_MBmodified.csv") %>% 
  filter(groupID != "T") %>%  #remove tap water controls
  select(!sampleID) %>% #remove sample id because estimates are at the tank-level
  unique() %>%
  rename(tank_ID = groupID) %>% 
  select(tank_ID, AC_biomass, PC_biomass, WP_biomass, AC_Fbiomass, PC_Fbiomass, WP_Fbiomass) %>%
  pivot_longer(cols = c(2:4), names_to = "taxon", values_to = "biomass") %>%
  pivot_longer(cols = c(2:4), names_to = "taxon2", values_to = "Fbiomass") %>%
  mutate(taxon = ifelse(taxon == "AC_biomass", "Boreogadus saida", taxon),
         taxon = ifelse(taxon == "PC_biomass", "Gadus macrocephalus", taxon),
         taxon = ifelse(taxon == "WP_biomass", "Gadus chalcogrammus", taxon)) %>%
  mutate(taxon2 = ifelse(taxon2 == "AC_Fbiomass", "Boreogadus saida", taxon2),
         taxon2 = ifelse(taxon2 == "PC_Fbiomass", "Gadus macrocephalus", taxon2),
         taxon2 = ifelse(taxon2 == "WP_Fbiomass", "Gadus chalcogrammus", taxon2)) %>%
  filter(taxon == taxon2) %>%
  select(!taxon2) %>%
  mutate(tank_ID = as.integer(tank_ID))
```

combine
```{r}
all <- aquaria_data %>%
  left_join(metadata, by = c("tank_ID", "taxon"))
```

what should be negative? 
```{r}
negatives <- all %>%
  filter(biomass == 0) %>%
  filter(prop_reads > 0.01)
```

how many experiments? 
```{r}
length(unique(negatives$tank_ID))
```

three of these were flagged for outliers in tank dissimilarity tests... 

